repos:
- repo: https://github.com/FriendsOfPHP/PHP-CS-Fixer
  rev: 7fc8eef
  hooks:
    - id: php-cs-fixer
      name: php-cs-fixer
      entry: php-cs-fixer fix --config=.php_cs --ansi --verbose --dry-run --diff
      language: system
      types: [php]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
